// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_ascclient.go -package=mocks ascClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	asc "github.com/tergrigoryantc/asc-mcp/internal/shared/asc"
	gomock "go.uber.org/mock/gomock"
)

// MockascClient is a mock of ascClient interface.
type MockascClient struct {
	ctrl     *gomock.Controller
	recorder *MockascClientMockRecorder
	isgomock struct{}
}

// MockascClientMockRecorder is the mock recorder for MockascClient.
type MockascClientMockRecorder struct {
	mock *MockascClient
}

// NewMockascClient creates a new mock instance.
func NewMockascClient(ctrl *gomock.Controller) *MockascClient {
	mock := &MockascClient{ctrl: ctrl}
	mock.recorder = &MockascClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockascClient) EXPECT() *MockascClientMockRecorder {
	return m.recorder
}

// CreateIAP mocks base method.
func (m *MockascClient) CreateIAP(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIAP", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIAP indicates an expected call of CreateIAP.
func (mr *MockascClientMockRecorder) CreateIAP(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIAP", reflect.TypeOf((*MockascClient)(nil).CreateIAP), ctx, payload)
}

// CreateIAPAvailability mocks base method.
func (m *MockascClient) CreateIAPAvailability(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIAPAvailability", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIAPAvailability indicates an expected call of CreateIAPAvailability.
func (mr *MockascClientMockRecorder) CreateIAPAvailability(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIAPAvailability", reflect.TypeOf((*MockascClient)(nil).CreateIAPAvailability), ctx, payload)
}

// CreateIAPLocalization mocks base method.
func (m *MockascClient) CreateIAPLocalization(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIAPLocalization", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIAPLocalization indicates an expected call of CreateIAPLocalization.
func (mr *MockascClientMockRecorder) CreateIAPLocalization(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIAPLocalization", reflect.TypeOf((*MockascClient)(nil).CreateIAPLocalization), ctx, payload)
}

// CreateIAPPriceSchedule mocks base method.
func (m *MockascClient) CreateIAPPriceSchedule(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIAPPriceSchedule", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIAPPriceSchedule indicates an expected call of CreateIAPPriceSchedule.
func (mr *MockascClientMockRecorder) CreateIAPPriceSchedule(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIAPPriceSchedule", reflect.TypeOf((*MockascClient)(nil).CreateIAPPriceSchedule), ctx, payload)
}

// CreateSubscription mocks base method.
func (m *MockascClient) CreateSubscription(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockascClientMockRecorder) CreateSubscription(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockascClient)(nil).CreateSubscription), ctx, payload)
}

// CreateSubscriptionAvailability mocks base method.
func (m *MockascClient) CreateSubscriptionAvailability(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptionAvailability", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriptionAvailability indicates an expected call of CreateSubscriptionAvailability.
func (mr *MockascClientMockRecorder) CreateSubscriptionAvailability(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionAvailability", reflect.TypeOf((*MockascClient)(nil).CreateSubscriptionAvailability), ctx, payload)
}

// CreateSubscriptionGroup mocks base method.
func (m *MockascClient) CreateSubscriptionGroup(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptionGroup", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriptionGroup indicates an expected call of CreateSubscriptionGroup.
func (mr *MockascClientMockRecorder) CreateSubscriptionGroup(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionGroup", reflect.TypeOf((*MockascClient)(nil).CreateSubscriptionGroup), ctx, payload)
}

// CreateSubscriptionGroupLocalization mocks base method.
func (m *MockascClient) CreateSubscriptionGroupLocalization(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptionGroupLocalization", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriptionGroupLocalization indicates an expected call of CreateSubscriptionGroupLocalization.
func (mr *MockascClientMockRecorder) CreateSubscriptionGroupLocalization(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionGroupLocalization", reflect.TypeOf((*MockascClient)(nil).CreateSubscriptionGroupLocalization), ctx, payload)
}

// CreateSubscriptionLocalization mocks base method.
func (m *MockascClient) CreateSubscriptionLocalization(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptionLocalization", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriptionLocalization indicates an expected call of CreateSubscriptionLocalization.
func (mr *MockascClientMockRecorder) CreateSubscriptionLocalization(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionLocalization", reflect.TypeOf((*MockascClient)(nil).CreateSubscriptionLocalization), ctx, payload)
}

// CreateSubscriptionPrice mocks base method.
func (m *MockascClient) CreateSubscriptionPrice(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptionPrice", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriptionPrice indicates an expected call of CreateSubscriptionPrice.
func (mr *MockascClientMockRecorder) CreateSubscriptionPrice(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionPrice", reflect.TypeOf((*MockascClient)(nil).CreateSubscriptionPrice), ctx, payload)
}

// GetAllTerritories mocks base method.
func (m *MockascClient) GetAllTerritories(ctx context.Context) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTerritories", ctx)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTerritories indicates an expected call of GetAllTerritories.
func (mr *MockascClientMockRecorder) GetAllTerritories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTerritories", reflect.TypeOf((*MockascClient)(nil).GetAllTerritories), ctx)
}

// GetAppIAPs mocks base method.
func (m *MockascClient) GetAppIAPs(ctx context.Context, appID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppIAPs", ctx, appID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppIAPs indicates an expected call of GetAppIAPs.
func (mr *MockascClientMockRecorder) GetAppIAPs(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppIAPs", reflect.TypeOf((*MockascClient)(nil).GetAppIAPs), ctx, appID)
}

// GetAppSubscriptionGroups mocks base method.
func (m *MockascClient) GetAppSubscriptionGroups(ctx context.Context, appID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppSubscriptionGroups", ctx, appID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppSubscriptionGroups indicates an expected call of GetAppSubscriptionGroups.
func (mr *MockascClientMockRecorder) GetAppSubscriptionGroups(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppSubscriptionGroups", reflect.TypeOf((*MockascClient)(nil).GetAppSubscriptionGroups), ctx, appID)
}

// GetGroupSubscriptions mocks base method.
func (m *MockascClient) GetGroupSubscriptions(ctx context.Context, groupID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupSubscriptions", ctx, groupID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupSubscriptions indicates an expected call of GetGroupSubscriptions.
func (mr *MockascClientMockRecorder) GetGroupSubscriptions(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupSubscriptions", reflect.TypeOf((*MockascClient)(nil).GetGroupSubscriptions), ctx, groupID)
}

// GetIAPLocalizations mocks base method.
func (m *MockascClient) GetIAPLocalizations(ctx context.Context, iapID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIAPLocalizations", ctx, iapID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIAPLocalizations indicates an expected call of GetIAPLocalizations.
func (mr *MockascClientMockRecorder) GetIAPLocalizations(ctx, iapID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIAPLocalizations", reflect.TypeOf((*MockascClient)(nil).GetIAPLocalizations), ctx, iapID)
}

// GetIAPPricePoints mocks base method.
func (m *MockascClient) GetIAPPricePoints(ctx context.Context, iapID, territory string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIAPPricePoints", ctx, iapID, territory)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIAPPricePoints indicates an expected call of GetIAPPricePoints.
func (mr *MockascClientMockRecorder) GetIAPPricePoints(ctx, iapID, territory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIAPPricePoints", reflect.TypeOf((*MockascClient)(nil).GetIAPPricePoints), ctx, iapID, territory)
}

// GetSubscriptionLocalizations mocks base method.
func (m *MockascClient) GetSubscriptionLocalizations(ctx context.Context, subscriptionID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionLocalizations", ctx, subscriptionID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionLocalizations indicates an expected call of GetSubscriptionLocalizations.
func (mr *MockascClientMockRecorder) GetSubscriptionLocalizations(ctx, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionLocalizations", reflect.TypeOf((*MockascClient)(nil).GetSubscriptionLocalizations), ctx, subscriptionID)
}

// GetSubscriptionPricePointEqualizations mocks base method.
func (m *MockascClient) GetSubscriptionPricePointEqualizations(ctx context.Context, pointID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionPricePointEqualizations", ctx, pointID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionPricePointEqualizations indicates an expected call of GetSubscriptionPricePointEqualizations.
func (mr *MockascClientMockRecorder) GetSubscriptionPricePointEqualizations(ctx, pointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionPricePointEqualizations", reflect.TypeOf((*MockascClient)(nil).GetSubscriptionPricePointEqualizations), ctx, pointID)
}

// GetSubscriptionPricePoints mocks base method.
func (m *MockascClient) GetSubscriptionPricePoints(ctx context.Context, subID, territory string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionPricePoints", ctx, subID, territory)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionPricePoints indicates an expected call of GetSubscriptionPricePoints.
func (mr *MockascClientMockRecorder) GetSubscriptionPricePoints(ctx, subID, territory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionPricePoints", reflect.TypeOf((*MockascClient)(nil).GetSubscriptionPricePoints), ctx, subID, territory)
}

// UpdateIAPLocalization mocks base method.
func (m *MockascClient) UpdateIAPLocalization(ctx context.Context, id string, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIAPLocalization", ctx, id, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIAPLocalization indicates an expected call of UpdateIAPLocalization.
func (mr *MockascClientMockRecorder) UpdateIAPLocalization(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIAPLocalization", reflect.TypeOf((*MockascClient)(nil).UpdateIAPLocalization), ctx, id, payload)
}

// UpdateSubscriptionLocalization mocks base method.
func (m *MockascClient) UpdateSubscriptionLocalization(ctx context.Context, id string, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionLocalization", ctx, id, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubscriptionLocalization indicates an expected call of UpdateSubscriptionLocalization.
func (mr *MockascClientMockRecorder) UpdateSubscriptionLocalization(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionLocalization", reflect.TypeOf((*MockascClient)(nil).UpdateSubscriptionLocalization), ctx, id, payload)
}
