// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_ascclient.go -package=mocks ascClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	asc "github.com/tergrigoryantc/asc-mcp/internal/shared/asc"
	gomock "go.uber.org/mock/gomock"
)

// MockascClient is a mock of ascClient interface.
type MockascClient struct {
	ctrl     *gomock.Controller
	recorder *MockascClientMockRecorder
	isgomock struct{}
}

// MockascClientMockRecorder is the mock recorder for MockascClient.
type MockascClientMockRecorder struct {
	mock *MockascClient
}

// NewMockascClient creates a new mock instance.
func NewMockascClient(ctrl *gomock.Controller) *MockascClient {
	mock := &MockascClient{ctrl: ctrl}
	mock.recorder = &MockascClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockascClient) EXPECT() *MockascClientMockRecorder {
	return m.recorder
}

// CommitIAPReviewScreenshot mocks base method.
func (m *MockascClient) CommitIAPReviewScreenshot(ctx context.Context, id string, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitIAPReviewScreenshot", ctx, id, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitIAPReviewScreenshot indicates an expected call of CommitIAPReviewScreenshot.
func (mr *MockascClientMockRecorder) CommitIAPReviewScreenshot(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitIAPReviewScreenshot", reflect.TypeOf((*MockascClient)(nil).CommitIAPReviewScreenshot), ctx, id, payload)
}

// CommitScreenshot mocks base method.
func (m *MockascClient) CommitScreenshot(ctx context.Context, id string, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitScreenshot", ctx, id, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitScreenshot indicates an expected call of CommitScreenshot.
func (mr *MockascClientMockRecorder) CommitScreenshot(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitScreenshot", reflect.TypeOf((*MockascClient)(nil).CommitScreenshot), ctx, id, payload)
}

// CommitSubscriptionReviewScreenshot mocks base method.
func (m *MockascClient) CommitSubscriptionReviewScreenshot(ctx context.Context, id string, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitSubscriptionReviewScreenshot", ctx, id, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitSubscriptionReviewScreenshot indicates an expected call of CommitSubscriptionReviewScreenshot.
func (mr *MockascClientMockRecorder) CommitSubscriptionReviewScreenshot(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitSubscriptionReviewScreenshot", reflect.TypeOf((*MockascClient)(nil).CommitSubscriptionReviewScreenshot), ctx, id, payload)
}

// CreateScreenshotSet mocks base method.
func (m *MockascClient) CreateScreenshotSet(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScreenshotSet", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScreenshotSet indicates an expected call of CreateScreenshotSet.
func (mr *MockascClientMockRecorder) CreateScreenshotSet(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScreenshotSet", reflect.TypeOf((*MockascClient)(nil).CreateScreenshotSet), ctx, payload)
}

// DeleteIAPReviewScreenshot mocks base method.
func (m *MockascClient) DeleteIAPReviewScreenshot(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIAPReviewScreenshot", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIAPReviewScreenshot indicates an expected call of DeleteIAPReviewScreenshot.
func (mr *MockascClientMockRecorder) DeleteIAPReviewScreenshot(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIAPReviewScreenshot", reflect.TypeOf((*MockascClient)(nil).DeleteIAPReviewScreenshot), ctx, id)
}

// DeleteScreenshot mocks base method.
func (m *MockascClient) DeleteScreenshot(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScreenshot", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScreenshot indicates an expected call of DeleteScreenshot.
func (mr *MockascClientMockRecorder) DeleteScreenshot(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScreenshot", reflect.TypeOf((*MockascClient)(nil).DeleteScreenshot), ctx, id)
}

// DeleteScreenshotSet mocks base method.
func (m *MockascClient) DeleteScreenshotSet(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScreenshotSet", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScreenshotSet indicates an expected call of DeleteScreenshotSet.
func (mr *MockascClientMockRecorder) DeleteScreenshotSet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScreenshotSet", reflect.TypeOf((*MockascClient)(nil).DeleteScreenshotSet), ctx, id)
}

// DeleteSubscriptionReviewScreenshot mocks base method.
func (m *MockascClient) DeleteSubscriptionReviewScreenshot(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptionReviewScreenshot", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptionReviewScreenshot indicates an expected call of DeleteSubscriptionReviewScreenshot.
func (mr *MockascClientMockRecorder) DeleteSubscriptionReviewScreenshot(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptionReviewScreenshot", reflect.TypeOf((*MockascClient)(nil).DeleteSubscriptionReviewScreenshot), ctx, id)
}

// GetIAPReviewScreenshot mocks base method.
func (m *MockascClient) GetIAPReviewScreenshot(ctx context.Context, iapID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIAPReviewScreenshot", ctx, iapID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIAPReviewScreenshot indicates an expected call of GetIAPReviewScreenshot.
func (mr *MockascClientMockRecorder) GetIAPReviewScreenshot(ctx, iapID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIAPReviewScreenshot", reflect.TypeOf((*MockascClient)(nil).GetIAPReviewScreenshot), ctx, iapID)
}

// GetSetScreenshots mocks base method.
func (m *MockascClient) GetSetScreenshots(ctx context.Context, setID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetScreenshots", ctx, setID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetScreenshots indicates an expected call of GetSetScreenshots.
func (mr *MockascClientMockRecorder) GetSetScreenshots(ctx, setID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetScreenshots", reflect.TypeOf((*MockascClient)(nil).GetSetScreenshots), ctx, setID)
}

// GetSubscriptionReviewScreenshot mocks base method.
func (m *MockascClient) GetSubscriptionReviewScreenshot(ctx context.Context, subID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionReviewScreenshot", ctx, subID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionReviewScreenshot indicates an expected call of GetSubscriptionReviewScreenshot.
func (mr *MockascClientMockRecorder) GetSubscriptionReviewScreenshot(ctx, subID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionReviewScreenshot", reflect.TypeOf((*MockascClient)(nil).GetSubscriptionReviewScreenshot), ctx, subID)
}

// GetVersionLocScreenshotSets mocks base method.
func (m *MockascClient) GetVersionLocScreenshotSets(ctx context.Context, versionLocID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersionLocScreenshotSets", ctx, versionLocID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersionLocScreenshotSets indicates an expected call of GetVersionLocScreenshotSets.
func (mr *MockascClientMockRecorder) GetVersionLocScreenshotSets(ctx, versionLocID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersionLocScreenshotSets", reflect.TypeOf((*MockascClient)(nil).GetVersionLocScreenshotSets), ctx, versionLocID)
}

// ReserveIAPReviewScreenshot mocks base method.
func (m *MockascClient) ReserveIAPReviewScreenshot(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveIAPReviewScreenshot", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveIAPReviewScreenshot indicates an expected call of ReserveIAPReviewScreenshot.
func (mr *MockascClientMockRecorder) ReserveIAPReviewScreenshot(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveIAPReviewScreenshot", reflect.TypeOf((*MockascClient)(nil).ReserveIAPReviewScreenshot), ctx, payload)
}

// ReserveScreenshot mocks base method.
func (m *MockascClient) ReserveScreenshot(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveScreenshot", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveScreenshot indicates an expected call of ReserveScreenshot.
func (mr *MockascClientMockRecorder) ReserveScreenshot(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveScreenshot", reflect.TypeOf((*MockascClient)(nil).ReserveScreenshot), ctx, payload)
}

// ReserveSubscriptionReviewScreenshot mocks base method.
func (m *MockascClient) ReserveSubscriptionReviewScreenshot(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveSubscriptionReviewScreenshot", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveSubscriptionReviewScreenshot indicates an expected call of ReserveSubscriptionReviewScreenshot.
func (mr *MockascClientMockRecorder) ReserveSubscriptionReviewScreenshot(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveSubscriptionReviewScreenshot", reflect.TypeOf((*MockascClient)(nil).ReserveSubscriptionReviewScreenshot), ctx, payload)
}

// UploadChunk mocks base method.
func (m *MockascClient) UploadChunk(ctx context.Context, method, url string, headers map[string]string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadChunk", ctx, method, url, headers, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadChunk indicates an expected call of UploadChunk.
func (mr *MockascClientMockRecorder) UploadChunk(ctx, method, url, headers, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadChunk", reflect.TypeOf((*MockascClient)(nil).UploadChunk), ctx, method, url, headers, data)
}
