// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_ascclient.go -package=mocks ascClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	asc "github.com/tergrigoryantc/asc-mcp/internal/shared/asc"
	gomock "go.uber.org/mock/gomock"
)

// MockascClient is a mock of ascClient interface.
type MockascClient struct {
	ctrl     *gomock.Controller
	recorder *MockascClientMockRecorder
	isgomock struct{}
}

// MockascClientMockRecorder is the mock recorder for MockascClient.
type MockascClientMockRecorder struct {
	mock *MockascClient
}

// NewMockascClient creates a new mock instance.
func NewMockascClient(ctrl *gomock.Controller) *MockascClient {
	mock := &MockascClient{ctrl: ctrl}
	mock.recorder = &MockascClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockascClient) EXPECT() *MockascClientMockRecorder {
	return m.recorder
}

// CreateAppInfoLocalization mocks base method.
func (m *MockascClient) CreateAppInfoLocalization(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppInfoLocalization", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppInfoLocalization indicates an expected call of CreateAppInfoLocalization.
func (mr *MockascClientMockRecorder) CreateAppInfoLocalization(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppInfoLocalization", reflect.TypeOf((*MockascClient)(nil).CreateAppInfoLocalization), ctx, payload)
}

// CreateVersionLocalization mocks base method.
func (m *MockascClient) CreateVersionLocalization(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVersionLocalization", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVersionLocalization indicates an expected call of CreateVersionLocalization.
func (mr *MockascClientMockRecorder) CreateVersionLocalization(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVersionLocalization", reflect.TypeOf((*MockascClient)(nil).CreateVersionLocalization), ctx, payload)
}

// GetVersionLocalizations mocks base method.
func (m *MockascClient) GetVersionLocalizations(ctx context.Context, versionID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersionLocalizations", ctx, versionID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersionLocalizations indicates an expected call of GetVersionLocalizations.
func (mr *MockascClientMockRecorder) GetVersionLocalizations(ctx, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersionLocalizations", reflect.TypeOf((*MockascClient)(nil).GetVersionLocalizations), ctx, versionID)
}

// UpdateAppInfoLocalization mocks base method.
func (m *MockascClient) UpdateAppInfoLocalization(ctx context.Context, id string, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppInfoLocalization", ctx, id, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAppInfoLocalization indicates an expected call of UpdateAppInfoLocalization.
func (mr *MockascClientMockRecorder) UpdateAppInfoLocalization(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppInfoLocalization", reflect.TypeOf((*MockascClient)(nil).UpdateAppInfoLocalization), ctx, id, payload)
}

// UpdateVersionLocalization mocks base method.
func (m *MockascClient) UpdateVersionLocalization(ctx context.Context, id string, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVersionLocalization", ctx, id, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVersionLocalization indicates an expected call of UpdateVersionLocalization.
func (mr *MockascClientMockRecorder) UpdateVersionLocalization(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVersionLocalization", reflect.TypeOf((*MockascClient)(nil).UpdateVersionLocalization), ctx, id, payload)
}
