// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/submission/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/submission/service.go -destination=internal/features/submission/mocks/mock_ascclient.go -package=mocks ascClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	asc "github.com/tergrigoryantc/asc-mcp/internal/shared/asc"
	gomock "go.uber.org/mock/gomock"
)

// MockascClient is a mock of ascClient interface.
type MockascClient struct {
	ctrl     *gomock.Controller
	recorder *MockascClientMockRecorder
	isgomock struct{}
}

// MockascClientMockRecorder is the mock recorder for MockascClient.
type MockascClientMockRecorder struct {
	mock *MockascClient
}

// NewMockascClient creates a new mock instance.
func NewMockascClient(ctrl *gomock.Controller) *MockascClient {
	mock := &MockascClient{ctrl: ctrl}
	mock.recorder = &MockascClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockascClient) EXPECT() *MockascClientMockRecorder {
	return m.recorder
}

// CreateReviewSubmission mocks base method.
func (m *MockascClient) CreateReviewSubmission(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReviewSubmission", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReviewSubmission indicates an expected call of CreateReviewSubmission.
func (mr *MockascClientMockRecorder) CreateReviewSubmission(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReviewSubmission", reflect.TypeOf((*MockascClient)(nil).CreateReviewSubmission), ctx, payload)
}

// CreateReviewSubmissionItem mocks base method.
func (m *MockascClient) CreateReviewSubmissionItem(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReviewSubmissionItem", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReviewSubmissionItem indicates an expected call of CreateReviewSubmissionItem.
func (mr *MockascClientMockRecorder) CreateReviewSubmissionItem(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReviewSubmissionItem", reflect.TypeOf((*MockascClient)(nil).CreateReviewSubmissionItem), ctx, payload)
}

// GetReviewSubmission mocks base method.
func (m *MockascClient) GetReviewSubmission(ctx context.Context, id string) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewSubmission", ctx, id)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewSubmission indicates an expected call of GetReviewSubmission.
func (mr *MockascClientMockRecorder) GetReviewSubmission(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewSubmission", reflect.TypeOf((*MockascClient)(nil).GetReviewSubmission), ctx, id)
}

// UpdateReviewSubmission mocks base method.
func (m *MockascClient) UpdateReviewSubmission(ctx context.Context, id string, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReviewSubmission", ctx, id, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReviewSubmission indicates an expected call of UpdateReviewSubmission.
func (mr *MockascClientMockRecorder) UpdateReviewSubmission(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReviewSubmission", reflect.TypeOf((*MockascClient)(nil).UpdateReviewSubmission), ctx, id, payload)
}
