// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/versions/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/versions/service.go -destination=internal/features/versions/mocks/mock_ascclient.go -package=mocks ascClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	asc "github.com/tergeoo/asc-mcp/internal/shared/asc"
	gomock "go.uber.org/mock/gomock"
)

// MockascClient is a mock of ascClient interface.
type MockascClient struct {
	ctrl     *gomock.Controller
	recorder *MockascClientMockRecorder
	isgomock struct{}
}

// MockascClientMockRecorder is the mock recorder for MockascClient.
type MockascClientMockRecorder struct {
	mock *MockascClient
}

// NewMockascClient creates a new mock instance.
func NewMockascClient(ctrl *gomock.Controller) *MockascClient {
	mock := &MockascClient{ctrl: ctrl}
	mock.recorder = &MockascClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockascClient) EXPECT() *MockascClientMockRecorder {
	return m.recorder
}

// CreateVersion mocks base method.
func (m *MockascClient) CreateVersion(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVersion", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVersion indicates an expected call of CreateVersion.
func (mr *MockascClientMockRecorder) CreateVersion(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVersion", reflect.TypeOf((*MockascClient)(nil).CreateVersion), ctx, payload)
}

// GetAppVersions mocks base method.
func (m *MockascClient) GetAppVersions(ctx context.Context, appID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppVersions", ctx, appID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppVersions indicates an expected call of GetAppVersions.
func (mr *MockascClientMockRecorder) GetAppVersions(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppVersions", reflect.TypeOf((*MockascClient)(nil).GetAppVersions), ctx, appID)
}

// GetVersion mocks base method.
func (m *MockascClient) GetVersion(ctx context.Context, id string) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, id)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockascClientMockRecorder) GetVersion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockascClient)(nil).GetVersion), ctx, id)
}

// UpdateVersion mocks base method.
func (m *MockascClient) UpdateVersion(ctx context.Context, id string, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVersion", ctx, id, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVersion indicates an expected call of UpdateVersion.
func (mr *MockascClientMockRecorder) UpdateVersion(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVersion", reflect.TypeOf((*MockascClient)(nil).UpdateVersion), ctx, id, payload)
}
