// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_ascclient.go -package=mocks ascClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	asc "github.com/tergrigoryantc/asc-mcp/internal/shared/asc"
	gomock "go.uber.org/mock/gomock"
)

// MockascClient is a mock of ascClient interface.
type MockascClient struct {
	ctrl     *gomock.Controller
	recorder *MockascClientMockRecorder
	isgomock struct{}
}

// MockascClientMockRecorder is the mock recorder for MockascClient.
type MockascClientMockRecorder struct {
	mock *MockascClient
}

// NewMockascClient creates a new mock instance.
func NewMockascClient(ctrl *gomock.Controller) *MockascClient {
	mock := &MockascClient{ctrl: ctrl}
	mock.recorder = &MockascClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockascClient) EXPECT() *MockascClientMockRecorder {
	return m.recorder
}

// CreateAppAvailability mocks base method.
func (m *MockascClient) CreateAppAvailability(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppAvailability", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppAvailability indicates an expected call of CreateAppAvailability.
func (mr *MockascClientMockRecorder) CreateAppAvailability(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppAvailability", reflect.TypeOf((*MockascClient)(nil).CreateAppAvailability), ctx, payload)
}

// CreateAppPriceSchedule mocks base method.
func (m *MockascClient) CreateAppPriceSchedule(ctx context.Context, payload any) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppPriceSchedule", ctx, payload)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppPriceSchedule indicates an expected call of CreateAppPriceSchedule.
func (mr *MockascClientMockRecorder) CreateAppPriceSchedule(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppPriceSchedule", reflect.TypeOf((*MockascClient)(nil).CreateAppPriceSchedule), ctx, payload)
}

// GetAllTerritories mocks base method.
func (m *MockascClient) GetAllTerritories(ctx context.Context) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTerritories", ctx)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTerritories indicates an expected call of GetAllTerritories.
func (mr *MockascClientMockRecorder) GetAllTerritories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTerritories", reflect.TypeOf((*MockascClient)(nil).GetAllTerritories), ctx)
}

// GetApp mocks base method.
func (m *MockascClient) GetApp(ctx context.Context, id string) (asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApp", ctx, id)
	ret0, _ := ret[0].(asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApp indicates an expected call of GetApp.
func (mr *MockascClientMockRecorder) GetApp(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApp", reflect.TypeOf((*MockascClient)(nil).GetApp), ctx, id)
}

// GetAppInfoLocalizations mocks base method.
func (m *MockascClient) GetAppInfoLocalizations(ctx context.Context, appInfoID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppInfoLocalizations", ctx, appInfoID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppInfoLocalizations indicates an expected call of GetAppInfoLocalizations.
func (mr *MockascClientMockRecorder) GetAppInfoLocalizations(ctx, appInfoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppInfoLocalizations", reflect.TypeOf((*MockascClient)(nil).GetAppInfoLocalizations), ctx, appInfoID)
}

// GetAppInfos mocks base method.
func (m *MockascClient) GetAppInfos(ctx context.Context, appID string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppInfos", ctx, appID)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppInfos indicates an expected call of GetAppInfos.
func (mr *MockascClientMockRecorder) GetAppInfos(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppInfos", reflect.TypeOf((*MockascClient)(nil).GetAppInfos), ctx, appID)
}

// GetAppPricePoints mocks base method.
func (m *MockascClient) GetAppPricePoints(ctx context.Context, appID, territory string) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppPricePoints", ctx, appID, territory)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppPricePoints indicates an expected call of GetAppPricePoints.
func (mr *MockascClientMockRecorder) GetAppPricePoints(ctx, appID, territory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppPricePoints", reflect.TypeOf((*MockascClient)(nil).GetAppPricePoints), ctx, appID, territory)
}

// ListApps mocks base method.
func (m *MockascClient) ListApps(ctx context.Context) ([]asc.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApps", ctx)
	ret0, _ := ret[0].([]asc.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApps indicates an expected call of ListApps.
func (mr *MockascClientMockRecorder) ListApps(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApps", reflect.TypeOf((*MockascClient)(nil).ListApps), ctx)
}
